Add search-form html and sass for all versions
AlonaStasyshyna/event-booster pull request #8
Opened 2022-09-15 19:37 UTC by AlexeyKiselyov

2022-09-15 20:14 UTC, AlonaStasyshyna requested changes

2022-09-15 20:14 UTC, AlonaStasyshyna commented on src/sass/layout/_search-form.scss
> +  margin-bottom: 24px;
ты сначала устанавливаешь этот маржин, а потом обнуляешь его на след. селекторе
попробуй сделать через first или last child, тогда и доп класс "--last "  тебе не будет нужен

2022-09-15 20:14 UTC, AlonaStasyshyna commented on src/sass/layout/_search-form.scss
> +  height: 40px;
я бы высоту сделала только за счет паддингов

2022-09-15 20:14 UTC, AlonaStasyshyna commented on src/sass/layout/_search-form.scss
> +    margin-right: 32px;
тут та же история с маржином, что и выше

2022-09-15 20:14 UTC, AlonaStasyshyna commented on src/partials/search-form.html
> +      <svg class="search-form__icon" width="18" height="15">
размеры по макету 15х10

2022-09-15 20:14 UTC, AlonaStasyshyna commented on src/partials/search-form.html
> +      <svg class="search-form__icon" width="18" height="15">
размеры по макету 12х12

2022-09-16 05:02 UTC, AlexeyKiselyov commented on src/partials/search-form.html
> +      <svg class="search-form__icon" width="18" height="15">
По макету 12х10, но при таком размере он сильно маленький визуально, мне как-то не нравится. Из того, что Артем сказал, я понял что можно корректировать дизайн, вот и взял на себя принять такое решение.

2022-09-16 05:08 UTC, AlexeyKiselyov commented on src/partials/search-form.html
> +      <svg class="search-form__icon" width="18" height="15">
Ты знаешь, на мобильной версии 12х10, на таблете вообще нет, на десктопе 12х12. Сделаю как на десктопе тогда везде.

2022-09-16 05:18 UTC, AlexeyKiselyov commented on src/sass/layout/_search-form.scss
> +  height: 40px;
Этот контейнер у меня родительский и я должен четко к нему спозиционировать иконки.

2022-09-16 05:22 UTC, AlexeyKiselyov commented on src/sass/layout/_search-form.scss
> +    margin-right: 32px;
За макароны согласен, но так мне показалось бытрее)

2022-09-16 07:44 UTC, AlonaStasyshyna approved these changes

2022-09-16 07:44 UTC, merged